# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Libops < Formula
  desc ""
  homepage "https://github.com/libops/homebrew-cli"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/LibOps/homebrew-cli/releases/download/v0.4.0/homebrew-cli_Darwin_arm64.tar.gz"
      sha256 "a191fbc05db493d446c92b74eaa2e0139244c44975cefadf5f54a24da1ca5338"

      def install
        bin.install "libops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/LibOps/homebrew-cli/releases/download/v0.4.0/homebrew-cli_Darwin_x86_64.tar.gz"
      sha256 "27d43286c2f8fcc2a3eca5ff825157877eb896072b9c03ab26ba47569109cab0"

      def install
        bin.install "libops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LibOps/homebrew-cli/releases/download/v0.4.0/homebrew-cli_Linux_arm64.tar.gz"
      sha256 "41708e3a3d7445c58ec648c4ca5bdd9add57bc1a1cc40237b6447cf101c5cde5"

      def install
        bin.install "libops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/LibOps/homebrew-cli/releases/download/v0.4.0/homebrew-cli_Linux_x86_64.tar.gz"
      sha256 "b380aa5cf5ae2ff6f104041a5e528fb2aaa12a9cf260fc7e3288042a420a40da"

      def install
        bin.install "libops"
      end
    end
  end
end
